//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebApi.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoppingMallEntities1 : DbContext
    {
        public ShoppingMallEntities1()
            : base("name=ShoppingMallEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCardMaster> tblCardMasters { get; set; }
        public virtual DbSet<tblItemMaster> tblItemMasters { get; set; }
        public virtual DbSet<tblItemType> tblItemTypes { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblPurchase> tblPurchases { get; set; }
        public virtual DbSet<tblPurchaseDetail> tblPurchaseDetails { get; set; }
        public virtual DbSet<tblReg> tblRegs { get; set; }
        public virtual DbSet<tblSale> tblSales { get; set; }
        public virtual DbSet<tblSaleDetail> tblSaleDetails { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
    }
}
