//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ShopName { get; set; }
        public string SupplierName { get; set; }
        public string Address { get; set; }
        public string GST { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public long srno { get; set; }
    }
}
