//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseDetail
    {
        public Nullable<long> ID { get; set; }
        public string ItemType { get; set; }
        public string ItemName { get; set; }
        public string ItemNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string HSN { get; set; }
        public long srno { get; set; }
    }
}
