//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReg
    {
        public long Regid { get; set; }
        public string CustomerName { get; set; }
        public string Custaddress { get; set; }
        public string MobileNo { get; set; }
        public string PinNo { get; set; }
    }
}
