//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public Nullable<long> StockID { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public string ItemNo { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> StockRate { get; set; }
        public long Srno { get; set; }
    }
}
