//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleDetail
    {
        public long SaleID { get; set; }
        public string SaleItemName { get; set; }
        public string SaleItemNo { get; set; }
        public Nullable<decimal> SaleQty { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<System.DateTime> sDate { get; set; }
        public long srno { get; set; }
    }
}
